#This is a Dockerfile used to create a containter for using this library
FROM continuumio/miniconda3


RUN conda install -c conda-forge -c intbio mdanalysis pandas pytest pypkg_example #TODO change pypkg_example to you package name


CMD [ "/bin/bash" ]